name: C/C++ stm32 build for the open-source embedded libraries

on:
  push:
    branches: [ 'main' ]
    paths: ['STM32/**', '.github/workflows/stm32build.yml']
  pull_request: 
    branches: [ 'main' ]
    paths: ['STM32/**', '.github/workflows/stm32build.yml']

jobs: 
  # Run unittest
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3   
    # Build and run unittests. If the unittest fails the line number is output.
    - name: Run unittests
      run: |
        cd "STM32/UnitTesting"
        cmake CMakeLists.txt
        make
        output=$(./CA_UnitTesting)
        echo $output
        if [[ $output =~ "failed" ]]; then 
          echo "Test failed"
          exit 1
        fi
